/**
 * AI Explanation Tab - M9 LLM explanations
 */
import { useState } from 'react';
import axios from 'axios';

const AIExplanationTab = ({ jobId }) => {
  const [explanation, setExplanation] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);

  const handleGenerate = async () => {
    if (!jobId) {
      setError('No job ID available');
      return;
    }

    setLoading(true);
    setError(null);

    try {
      const response = await axios.post(`/api/v1/videos/${jobId}/explanation`);
      setExplanation(response.data);
    } catch (err) {
      console.error('Failed to generate explanation:', err);
      
      if (err.response?.status === 503) {
        setError('Ollama service is not running. Start Ollama and ensure qwen3:8b model is available.');
      } else if (err.response?.status === 400) {
        setError(err.response.data.detail || 'Processing not completed or no M8 scene available.');
      } else {
        setError(err.response?.data?.detail || 'Failed to generate explanation. Check backend logs.');
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ padding: '20px', height: '100%', backgroundColor: '#0a0e1a' }}>
      <div style={{ 
        display: 'flex', 
        justifyContent: 'space-between', 
        alignItems: 'center', 
        marginBottom: '20px' 
      }}>
        <h3 style={{ margin: 0, color: '#e0e6ed', fontSize: '18px', fontWeight: '600' }}>
          AI-Generated Explanation
        </h3>
        
        <button
          onClick={handleGenerate}
          disabled={loading}
          style={{
            padding: '10px 20px',
            backgroundColor: loading ? '#374357' : '#5a9fd4',
            color: '#ffffff',
            border: 'none',
            borderRadius: '6px',
            fontSize: '14px',
            fontWeight: '500',
            cursor: loading ? 'not-allowed' : 'pointer',
            transition: 'all 0.2s',
            display: 'flex',
            alignItems: 'center',
            gap: '8px'
          }}
          onMouseEnter={(e) => {
            if (!loading) e.target.style.backgroundColor = '#4a8ec4';
          }}
          onMouseLeave={(e) => {
            if (!loading) e.target.style.backgroundColor = '#5a9fd4';
          }}
        >
          {loading ? (
            <>
              <span style={{ animation: 'spin 1s linear infinite' }}>⟳</span>
              Generating...
            </>
          ) : (
            <>
              <span>✨</span>
              Generate Explanation
            </>
          )}
        </button>
      </div>

      {/* Safety Notice */}
      <div style={{
        backgroundColor: '#1a2e3f',
        border: '1px solid #2d4a5c',
        borderRadius: '8px',
        padding: '15px',
        marginBottom: '25px',
        display: 'flex',
        gap: '12px'
      }}>
        <span style={{ fontSize: '20px', flexShrink: 0 }}>⚡</span>
        <div style={{ fontSize: '13px', color: '#8b95a8', lineHeight: '1.6' }}>
          <strong style={{ color: '#a0aab8' }}>AI Safety Notice:</strong> This explanation is generated by 
          Ollama/qwen3:8b based on M1-M8 evidence. The LLM acts as a <strong>narrator</strong>, not a detective. 
          It describes observable patterns without inferring intent, emotion, or threat.
        </div>
      </div>

      {/* Error State */}
      {error && (
        <div style={{
          backgroundColor: '#3d1f1f',
          border: '1px solid #6b3535',
          borderRadius: '8px',
          padding: '20px',
          marginBottom: '20px'
        }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '10px' }}>
            <span style={{ fontSize: '24px' }}>⚠️</span>
            <div style={{ fontSize: '16px', fontWeight: '600', color: '#ff8a80' }}>
              Generation Failed
            </div>
          </div>
          <div style={{ fontSize: '14px', color: '#d4a5a5', lineHeight: '1.6' }}>
            {error}
          </div>
        </div>
      )}

      {/* Loading State */}
      {loading && (
        <div style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '60px 20px',
          gap: '20px'
        }}>
          <div style={{
            width: '60px',
            height: '60px',
            border: '4px solid #1a2332',
            borderTop: '4px solid #5a9fd4',
            borderRadius: '50%',
            animation: 'spin 1s linear infinite'
          }} />
          <div style={{ fontSize: '16px', color: '#8b95a8', textAlign: 'center' }}>
            <div style={{ fontWeight: '600', marginBottom: '8px' }}>Generating Explanation</div>
            <div style={{ fontSize: '13px', color: '#6b7485' }}>
              Ollama is processing M8 scene evidence...
            </div>
          </div>
        </div>
      )}

      {/* Empty State (No explanation yet) */}
      {!loading && !error && !explanation && (
        <div style={{
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          justifyContent: 'center',
          padding: '60px 32px',
          backgroundColor: '#0d1220',
          border: '1px solid #1a2332',
          borderRadius: '12px',
          minHeight: '400px'
        }}>
          <div style={{
            width: '80px',
            height: '80px',
            borderRadius: '50%',
            backgroundColor: '#1a2332',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: '24px',
            border: '2px solid #243447'
          }}>
            <span style={{ fontSize: '36px', opacity: 0.6 }}>✨</span>
          </div>

          <div style={{
            fontSize: '20px',
            fontWeight: '600',
            color: '#e0e6ed',
            marginBottom: '12px',
            textAlign: 'center'
          }}>
            No Explanation Generated Yet
          </div>

          <div style={{
            fontSize: '14px',
            color: '#8b95a8',
            lineHeight: '1.7',
            marginBottom: '24px',
            textAlign: 'center',
            maxWidth: '480px'
          }}>
            Click <strong style={{ color: '#a0aab8' }}>&ldquo;Generate Explanation&rdquo;</strong> to invoke 
            Ollama/qwen3:8b and create a natural language narrative from the M8 contextual scene.
          </div>

          <div style={{
            fontSize: '13px',
            color: '#6b7485',
            padding: '12px 16px',
            backgroundColor: '#0a0e1a',
            borderRadius: '6px',
            border: '1px solid #1a2332'
          }}>
            <strong>Requirements:</strong> Ollama running at localhost:11434 with qwen3:8b model
          </div>
        </div>
      )}

      {/* Explanation Display */}
      {!loading && explanation && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          {/* Scene Overview */}
          <div style={{
            backgroundColor: '#0d1220',
            border: '1px solid #1a2332',
            borderLeft: '4px solid #5a9fd4',
            borderRadius: '8px',
            padding: '20px'
          }}>
            <div style={{ 
              display: 'flex', 
              alignItems: 'center', 
              gap: '10px', 
              marginBottom: '12px' 
            }}>
              <span style={{ fontSize: '24px' }}>📝</span>
              <h4 style={{ margin: 0, color: '#5a9fd4', fontSize: '16px', fontWeight: '600' }}>
                Scene Overview
              </h4>
            </div>
            <div style={{ fontSize: '14px', color: '#d4dae3', lineHeight: '1.8' }}>
              {explanation.overview || 'No overview provided'}
            </div>
          </div>

          {/* Entity Behaviors */}
          {explanation.entity_behaviors && explanation.entity_behaviors.length > 0 && (
            <div style={{
              backgroundColor: '#0d1220',
              border: '1px solid #1a2332',
              borderLeft: '4px solid #4caf50',
              borderRadius: '8px',
              padding: '20px'
            }}>
              <div style={{ 
                display: 'flex', 
                alignItems: 'center', 
                gap: '10px', 
                marginBottom: '16px' 
              }}>
                <span style={{ fontSize: '24px' }}>👥</span>
                <h4 style={{ margin: 0, color: '#4caf50', fontSize: '16px', fontWeight: '600' }}>
                  Entity Behaviors
                </h4>
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
                {explanation.entity_behaviors.map((entity, idx) => (
                  <div
                    key={idx}
                    style={{
                      padding: '14px',
                      backgroundColor: '#0a0e1a',
                      border: '1px solid #1a2332',
                      borderRadius: '6px'
                    }}
                  >
                    <div style={{ 
                      fontSize: '13px', 
                      fontWeight: '600', 
                      color: '#a0aab8', 
                      marginBottom: '8px',
                      display: 'flex',
                      alignItems: 'center',
                      gap: '8px'
                    }}>
                      <span style={{ 
                        width: '24px', 
                        height: '24px', 
                        borderRadius: '50%', 
                        backgroundColor: '#1a2332',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        fontSize: '11px'
                      }}>
                        {entity.track_id}
                      </span>
                      Track #{entity.track_id}
                    </div>
                    <div style={{ fontSize: '14px', color: '#d4dae3', lineHeight: '1.7' }}>
                      {entity.behavior_summary}
                    </div>
                    {entity.anomaly_explanations && entity.anomaly_explanations.length > 0 && (
                      <div style={{ marginTop: '10px', paddingTop: '10px', borderTop: '1px solid #1a2332' }}>
                        <div style={{ fontSize: '12px', color: '#8b95a8', marginBottom: '6px' }}>
                          Anomaly Types:
                        </div>
                        <div style={{ 
                          display: 'flex', 
                          flexWrap: 'wrap', 
                          gap: '6px' 
                        }}>
                          {entity.anomaly_explanations.map((anomaly, i) => (
                            <span
                              key={i}
                              style={{
                                padding: '4px 10px',
                                backgroundColor: '#ff980022',
                                border: '1px solid #ff980044',
                                borderRadius: '4px',
                                fontSize: '11px',
                                color: '#ffb74d'
                              }}
                            >
                              {anomaly.replace(/_/g, ' ')}
                            </span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Pattern Significance */}
          {explanation.pattern_significance && Object.keys(explanation.pattern_significance).length > 0 && (
            <div style={{
              backgroundColor: '#0d1220',
              border: '1px solid #1a2332',
              borderLeft: '4px solid #ff9800',
              borderRadius: '8px',
              padding: '20px'
            }}>
              <div style={{ 
                display: 'flex', 
                alignItems: 'center', 
                gap: '10px', 
                marginBottom: '12px' 
              }}>
                <span style={{ fontSize: '24px' }}>🔍</span>
                <h4 style={{ margin: 0, color: '#ff9800', fontSize: '16px', fontWeight: '600' }}>
                  Notable Patterns
                </h4>
              </div>
              <div style={{ fontSize: '14px', color: '#d4dae3', lineHeight: '1.8', whiteSpace: 'pre-wrap' }}>
                {Object.entries(explanation.pattern_significance).map(([pattern, significance], idx) => (
                  <div key={idx} style={{ marginBottom: '12px' }}>
                    <div style={{ fontWeight: '600', color: '#ffb74d', marginBottom: '4px' }}>
                      {pattern.replace(/_/g, ' ')}
                    </div>
                    <div>{significance}</div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Anomaly Significance */}
          {explanation.anomaly_significance && explanation.anomaly_significance.length > 0 && (
            <div style={{
              backgroundColor: '#0d1220',
              border: '1px solid #1a2332',
              borderLeft: '4px solid #f44336',
              borderRadius: '8px',
              padding: '20px'
            }}>
              <div style={{ 
                display: 'flex', 
                alignItems: 'center', 
                gap: '10px', 
                marginBottom: '12px' 
              }}>
                <span style={{ fontSize: '24px' }}>⚠️</span>
                <h4 style={{ margin: 0, color: '#f44336', fontSize: '16px', fontWeight: '600' }}>
                  Anomaly Analysis
                </h4>
              </div>
              <div style={{ fontSize: '14px', color: '#d4dae3', lineHeight: '1.8' }}>
                {explanation.anomaly_significance.filter(s => s).join('\n\n')}
              </div>
            </div>
          )}

          {/* Contextual Interpretation */}
          {explanation.contextual_interpretation && (
            <div style={{
              backgroundColor: '#0d1220',
              border: '1px solid #1a2332',
              borderLeft: '4px solid #9c27b0',
              borderRadius: '8px',
              padding: '20px'
            }}>
              <div style={{ 
                display: 'flex', 
                alignItems: 'center', 
                gap: '10px', 
                marginBottom: '12px' 
              }}>
                <span style={{ fontSize: '24px' }}>🤖</span>
                <h4 style={{ margin: 0, color: '#9c27b0', fontSize: '16px', fontWeight: '600' }}>
                  AI Interpretation
                </h4>
              </div>
              <div style={{ fontSize: '14px', color: '#d4dae3', lineHeight: '1.8', whiteSpace: 'pre-wrap' }}>
                {explanation.contextual_interpretation}
              </div>
            </div>
          )}

          {/* Metadata Footer */}
          <div style={{
            padding: '16px',
            backgroundColor: '#0d1220',
            borderRadius: '6px',
            border: '1px solid #1a2332',
            fontSize: '12px',
            color: '#6b7485',
            display: 'flex',
            gap: '16px',
            flexWrap: 'wrap'
          }}>
            {explanation.model_name && (
              <div>
                <strong style={{ color: '#8b95a8' }}>Model:</strong> {explanation.model_name}
              </div>
            )}
            {explanation.generated_at && (
              <div>
                <strong style={{ color: '#8b95a8' }}>Generated:</strong> {new Date(explanation.generated_at).toLocaleString()}
              </div>
            )}
            {explanation.generation_time_ms !== undefined && (
              <div>
                <strong style={{ color: '#8b95a8' }}>Generation Time:</strong> {explanation.generation_time_ms.toFixed(0)}ms
              </div>
            )}
            {explanation.confidence_level && (
              <div>
                <strong style={{ color: '#8b95a8' }}>Confidence:</strong> {explanation.confidence_level}
              </div>
            )}
            {explanation.evidence_coverage !== undefined && (
              <div>
                <strong style={{ color: '#8b95a8' }}>Evidence Coverage:</strong> {(explanation.evidence_coverage * 100).toFixed(0)}%
              </div>
            )}
            {explanation.is_fallback && (
              <div style={{ color: '#ff9800' }}>
                ⚠️ <strong>Fallback Mode:</strong> {explanation.fallback_reason || 'LLM unavailable'}
              </div>
            )}
          </div>
        </div>
      )}

      <style>{`
        @keyframes spin {
          0% { transform: rotate(0deg); }
          100% { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
};

export default AIExplanationTab;
